//Drums
export const hat = 'sound/steban/hat.mp3';
export const hat2 = 'sound/steban/hat2.mp3';
export const hat4 = 'sound/steban/hat4.mp3';
export const kick = 'sound/steban/kick.mp3';
export const snare = 'sound/steban/snare1.mp3';

//Piano
export const aK3 = 'sound/piano/a#3.mp3';
export const aK4 = 'sound/piano/a#4.mp3';
export const aK5 = 'sound/piano/a#5.mp3';
export const a3 = 'sound/piano/a3.mp3';
export const a4 = 'sound/piano/a4.mp3';
export const a5 = 'sound/piano/a5.mp3';
export const bK3 = 'sound/piano/b#3.mp3';
export const bK4 = 'sound/piano/b#4.mp3';
export const bK5 = 'sound/piano/b#5.mp3';
export const b3 = 'sound/piano/b3.mp3';
export const b4 = 'sound/piano/b4.mp3';
export const b5 = 'sound/piano/b5.mp3';
export const cK3 = 'sound/piano/c#3.mp3';
export const cK4 = 'sound/piano/c#4.mp3';
export const cK5 = 'sound/piano/c#5.mp3';
export const c3 = 'sound/piano/c3.mp3';
export const c4 = 'sound/piano/c4.mp3';
export const c5 = 'sound/piano/c5.mp3';
export const c6 = 'sound/piano/c6.mp3';
export const dK3 = 'sound/piano/d#3.mp3';
export const dK4 = 'sound/piano/d#4.mp3';
export const dK5 = 'sound/piano/d#5.mp3';
export const d3 = 'sound/piano/d3.mp3';
export const d4 = 'sound/piano/d4.mp3';
export const d5 = 'sound/piano/d5.mp3';
export const eK3 = 'sound/piano/e#3.mp3';
export const eK4 = 'sound/piano/e#4.mp3';
export const eK5 = 'sound/piano/e#5.mp3';
export const e3 = 'sound/piano/e3.mp3';
export const e4 = 'sound/piano/e4.mp3';
export const e5 = 'sound/piano/e5.mp3';
export const fK3 = 'sound/piano/f#3.mp3';
export const fK4 = 'sound/piano/f#4.mp3';
export const fK5 = 'sound/piano/f#5.mp3';
export const f3 = 'sound/piano/f3.mp3';
export const f4 = 'sound/piano/f4.mp3';
export const f5 = 'sound/piano/f5.mp3';
export const gK3 = 'sound/piano/g#3.mp3';
export const gK4 = 'sound/piano/g#4.mp3';
export const gK5 = 'sound/piano/g#5.mp3';
export const g3 = 'sound/piano/g3.mp3';
export const g4 = 'sound/piano/g4.mp3';
export const g5 = 'sound/piano/g5.mp3';

// export { kick, hat, hat2, hat4, snare };
